#!/bin/bash

TELEGRAM_BOT_TOKEN=7924775225:AAGe-ONQlQZJ2Ftj-MaOUMeFGsBr15D-zi0
TELEGRAM_USER_ID=678636670

CI_PROJECT_NAME=DO6_CICD-1

URL="https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
TEXT="Deploy status: $1%0A%0AProject:+$CI_PROJECT_NAME%0AURL:+$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID/%0ABranch:+$CI_COMMIT_REF_SLUG/%0A Выполнение CI/CD:$CI-успешно"

curl -s -d "chat_id=$TELEGRAM_USER_ID&disable_web_page_preview=1&text=$TEXT" $URL > /dev/null
