#!/bin/bash
SUDO_PASSWORD=00000
CAT=/home/gitlab-runner/builds/mpJmftMe/0/students/DO6_CICD.ID_356283/theiajar_student.school.ru/DO6_CICD-1/src/artifacts/cat
GREP=/home/gitlab-runner/builds/mpJmftMe/0/students/DO6_CICD.ID_356283/theiajar_student.school.ru/DO6_CICD-1/src/artifacts/rep
#USER= geortor
#IP_VM= 192.168.0.30

chmod 777 $S21_CAT $S21_GREP

#echo "HOST *" > ~/.ssh/config№
#echo "StrictHostKeyChecking no" >> ~/.ssh/config

scp -B $CAT $GREP geortor@192.168.0.27:/tmp
ssh "geortor@192.168.0.27" "echo $SUDO_PASSWORD | sudo su -S cp /tmp/cat /tmp/grep /usr/local/bin && chmod -R +x /usr/local/bin"

exit 0
